// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxadivuahkimoummnoca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4YWRpdnVhaGtpbW91bW1ub2NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzNDc1MjAsImV4cCI6MjA3OTkyMzUyMH0.rbLjc_fxKTouO3xaaAWjB7arVlgPxlIrXi6CYVXkpww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});